export const SupplierInfo = [
  {
    id: 1,
    companyName: 'Unilab',
    contactPerson: 'Chen E Lyn',
    contactNumber: '09564562315',
    companyEmail: 'unilab@gmail.com',
    address: '123 Apple St',
    city: 'Amsterdam',
    state: 'NY',
    zipCode: '5725',
    country: 'US',
  },
  {
    id: 2,
    companyName: 'Unilever',
    contactPerson: 'KinemberLyn',
    contactNumber: '09564562315',
    companyEmail: 'unilab@gmail.com',
    address: '123 Apple St',
    city: 'Amsterdam',
    state: 'NY',
    zipCode: '5725',
    country: 'US',
  },
  {
    id: 3,
    companyName: 'Paracetamol',
    contactPerson: 'Chen E Lyn',
    contactNumber: '09564562315',
    companyEmail: 'unilab@gmail.com',
    address: '123 Apple St',
    city: 'Amsterdam',
    state: 'NY',
    zipCode: '5725',
    country: 'US',
  },
  {
    id: 4,
    companyName: 'Antiseptic',
    contactPerson: 'Richard Yap',
    contactNumber: '09564562852',
    companyEmail: 'anti@gmail.com',
    address: '123 Mango St',
    city: 'California',
    state: 'NY',
    zipCode: '5725',
    country: 'US',
  },
  {
    id: 5,
    companyName: 'Paracetamol',
    contactPerson: 'Chen E Lyn',
    contactNumber: '09564562315',
    companyEmail: 'unilab@gmail.com',
    address: '123 Apple St',
    city: 'Amsterdam',
    state: 'NY',
    zipCode: '5725',
    country: 'US',
  },
  {
    id: 6,
    companyName: 'Paracetamol',
    contactPerson: 'Chen E Lyn',
    contactNumber: '09564562315',
    companyEmail: 'unilab@gmail.com',
    address: '123 Apple St',
    city: 'Amsterdam',
    state: 'NY',
    zipCode: '5725',
    country: 'US',
  },
  {
    id: 7,
    companyName: 'Paracetamol',
    contactPerson: 'Shiba',
    contactNumber: '09564562315',
    companyEmail: 'unilab@gmail.com',
    address: '123 Apple St',
    city: 'Amsterdam',
    state: 'NY',
    zipCode: '5725',
    country: 'US',
  },
  {
    id: 8,
    companyName: 'Arigato',
    contactPerson: 'Barbarita',
    contactNumber: '09564562315',
    companyEmail: 'unilab@gmail.com',
    address: '123 Apple St',
    city: 'Amsterdam',
    state: 'NY',
    zipCode: '5725',
    country: 'US',
  },
  {
    id: 9,
    companyName: 'Hola',
    contactPerson: 'Chen E Lyn',
    contactNumber: '09564562315',
    companyEmail: 'unilab@gmail.com',
    address: '123 Apple St',
    city: 'Amsterdam',
    state: 'NY',
    zipCode: '5725',
    country: 'US',
  },
  {
    id: 10,
    companyName: 'Hi',
    contactPerson: 'Chen E Lyn',
    contactNumber: '09564562315',
    companyEmail: 'unilab@gmail.com',
    address: '123 Apple St',
    city: 'Amsterdam',
    state: 'NY',
    zipCode: '5725',
    country: 'US',
  },
  {
    id: 11,
    companyName: 'Hello',
    contactPerson: 'Chen E Lyn',
    contactNumber: '09564562315',
    companyEmail: 'unilab@gmail.com',
    address: '123 Apple St',
    city: 'Amsterdam',
    state: 'NY',
    zipCode: '5725',
    country: 'US',
  },
]
export default SupplierInfo
