export const SupplierInfo = [
  {
    companyName: 'Unilab',
    contactPerson: 'Chen E Lyn',
    contactNumber: '09564562315',
    companyEmail: 'unilab@gmail.com',
    address: '123 Apple St',
    city: 'Amsterdam',
    state: 'NY',
    zipCode: '5725',
    country: 'US',
  },
  {
    companyName: 'Unilever',
    contactPerson: 'KinemberLyn',
    contactNumber: '09564562315',
    companyEmail: 'unilab@gmail.com',
    Address: '123 Apple St',
    City: 'Amsterdam',
    State: 'NY',
    ZipCode: '5725',
    Country: 'US',
  },
  {
    companyName: 'Paracetamol',
    contactPerson: 'Chen E Lyn',
    contactNumber: '09564562315',
    companyEmail: 'unilab@gmail.com',
    address: '123 Apple St',
    city: 'Amsterdam',
    state: 'NY',
    zipCode: '5725',
    country: 'US',
  },
]
export default SupplierInfo
